# Generated by Django 5.1.4 on 2025-01-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailhome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
