# Generated by Django 5.1.4 on 2025-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_home', '0003_alter_attachment_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailhome',
            name='signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
