# Generated by Django 5.1.6 on 2025-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_home", "0004_mailhome_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailhome",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mailhome",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
