# Generated by Django 5.1.6 on 2025-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_home", "0005_mailhome_deleted_at_mailhome_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailhome",
            name="subject",
            field=models.CharField(max_length=255),
        ),
    ]
